---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: redis-server-east
  namespace: default
spec:
  routingKey: redis-server-east
  port: 6381
  host: 127.0.0.1
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: redis-sentinel-east
  namespace: default
spec:
  routingKey: redis-sentinel-east
  port: 26381
  host: 127.0.0.1
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: redis-server-west
  namespace: default
spec:
  routingKey: redis-server-west
  port: 6380
  host: 127.0.0.1
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: redis-sentinel-west
  namespace: default
spec:
  routingKey: redis-sentinel-west
  port: 26380
  host: 127.0.0.1
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: redis-server-north
  namespace: default
spec:
  routingKey: redis-server-north
  port: 6379
  host: 127.0.0.1
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: redis-sentinel-north
  namespace: default
spec:
  routingKey: redis-sentinel-north
  port: 26379
  host: 127.0.0.1